# Add ./lib to the load path
$LOAD_PATH << File.expand_path( '../../lib' )

# require_relative '../../lib/statistrano'
require 'statistrano'

define_server "remote" do
  set :build_task, 'remote:copy'
  set :remote, 'digitalocean'
  set :local_dir, "build"
  set :project_root, '/var/www/testing.statistrano/remote_site'
end

namespace :remote do
  task :copy do
    `cp -r source/ build/`
  end
end