# Add ./lib to the load path
$LOAD_PATH << File.expand_path( '../../lib' )

# require_relative '../../lib/statistrano'
require 'statistrano'

define_server "remote" do
  set :build_task, 'remote:copy'
  set :remote, 'digitalocean'
  set :releases, false
  set :local_dir, "build"
  set :project_root, '/var/www/testing.statistrano/remote_post_deploy_task'
  set :base_domain, 'polar-refuge.com'
  set :public_dir, Statistrano::Util.monkey_name
  set :post_deploy_task, "post_deploy_task:run"
end

namespace :remote do
  task :copy do
    `cp -r source/ build/`
  end
end

namespace :post_deploy_task do
  task :run do
    puts "Ran Post Deploy Task"
  end
end