# Add ./lib to the load path
$LOAD_PATH << File.expand_path( '../../lib' )
require 'statistrano'

define_deployment "error" do |c|
	c.build_task = 'remote:copy'
	c.remote = 'localhost'
	c.local_dir = 'build'
	c.remote_dir = File.join( Dir.pwd, 'deployment' )
end

namespace :remote do
  task :copy do
    raise "error during the build"
  end
end